### ISSUE TITLE
Search / Autocomplete / UX Guidelines are incorrect

### ISSUE THREAD

**Issue by binx** [pelias/pelias-doc#127]
https://mapzen.com/documentation/search/autocomplete/#user-experience-guidelines

There should be more accurate rate limits than `a maximum of one or two requests per second`. The Mapzen search demo does not throttle at all, and the API seems to support this just fine. If there is a rate limit, it should be lower than 500-1000ms, because that is very high for a typing speed.

Secondly, the `requested_at` parameter is not returned in the API response. There is a `response.geocoding.timestamp` attribute, but it does not seem to act in the same manner as `requested_at` in the docs.

**Comment by orangejulius** [comment]
Yeah, we need to at least tell people to use our current per second rate limit (6 RPS or 166ms between requests). I'd love to see us eventually raise our per second rate limits or switch to per minute rate limits so that we can support 10-20 requests per seconds. I think that should be sufficient for a good autocomplete experience. Our API performance isn't always up to <100ms response times for autocomplete either :( but we'll get there.

The `requested_at` timestamp was mentioned before and we somehow totally missed that. I think `response.geocoding.timestamp` is calculated right before the response is sent, and then cached, meaning it wouldn't help discover responses that come back out of order. Looks like mapzen.js (via leaflet-geocoder-mapzen) [does its own tracking](https://github.com/mapzen/mapzen.js/blob/master/src/js/components/search.js#L314) for responses. I don't want to have to tell people to do this, but with our current caching setup I don't see another way :(

**Comment by kkowalsky** [comment]
updating this for the docs, @orangejulius should I just remove the info about 'requested_at'?
