### ISSUE TITLE
Cleanup TODO's in documents

### ISSUE THREAD

**Issue by riordan** [pelias/pelias-doc#19]
Edit or comment as you find em:

**Comment by rmglennon** [comment]
In the place search, it has an example to search for multiple values at once. I removed the TO DO text from the topic, but adding this note here for reference. I think this could use some explanatory text about the use case for multiple, unrelated location searches. For example, is it because you have different users searching in an end-user app and these random queries happen to come in at the same time, @stephenkhess?

"To search for more than one `/place` in a request, join multiple values together and separate them with a comma. For example, this /place query looks up the Eiffel Tower in OSM and `30 West 26th St, New York, NY` in OpenAddresses..."

**Comment by rmglennon** [comment]
In the search topic, in the table at the bottom, localadmin had TBD for its description. I was guessing it may have something to do with local administrative boundaries, so added that info for now.

**Comment by riordan** [comment]
@rmglennon The label field is used to include datasets to search. So if you want to search for everything but a particular data set (e.g. excluding GeoNames), you'd include all the other data sources you DO want to search (that we index in there).

This is the only field that operates as such (e.g. you can't search within two countries with the boundary.country=US,CA).
